services:
  # postgres:
  #   hostname: postgres
  #   image: postgres:18
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./data/pgsql:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: palpo_local
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - internal

  matrix-bridge-feishu:
    image: ghcr.io/palpo-im/matrix-bridge-feishu:main
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      RUST_LOG: matrix_bridge_feishu=debug,info
    # depends_on:
    #   postgres:
    #     condition: service_healthy
