services:
  # postgres:
  #   hostname: postgres
  #   image: postgres:18
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./data/pgsql:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: palpo_local
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - internal

  mautrix-telegram:
    image: dock.mau.dev/mautrix/telegram:latest
    restart: unless-stopped
    volumes:
      - ./data/mautrix-telegram:/data
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    ports:
      - 29317:29317
    networks:
      - internal

networks:
  internal:
    attachable: true
